""" Common fixtures for tests
"""

import pytest

only_manual = pytest.mark.skipif(True,
                                 reason="This test is very time consuming, "
                                        "so we run it manually when needed")


@pytest.fixture
def live_scoreboard_games():
    """Mock response from live scoreboard
    """
    return [
        {'awayTeam': {'inBonus': '0',
                      'losses': 1,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 40},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 30},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 28},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 5}],
                      'score': 103,
                      'seed': None,
                      'teamCity': 'Denver',
                      'teamId': 1610612743,
                      'teamName': 'Nuggets',
                      'teamTricode': 'DEN',
                      'timeoutsRemaining': 3,
                      'wins': 0},
         'gameClock': 'PT09M18.00S',
         'gameCode': '20221021/DENGSW',
         'gameEt': '2022-10-21T22:00:00-04:00',
         'gameId': '0022200026',
         'gameLeaders': {'awayLeaders': {'assists': 7,
                                         'jerseyNum': '15',
                                         'name': 'Nikola Jokic',
                                         'personId': 203999,
                                         'playerSlug': 'nikola-jokic',
                                         'points': 19,
                                         'position': 'C',
                                         'rebounds': 10,
                                         'teamTricode': 'DEN'},
                         'homeLeaders': {'assists': 4,
                                         'jerseyNum': '30',
                                         'name': 'Stephen Curry',
                                         'personId': 201939,
                                         'playerSlug': 'stephen-curry',
                                         'points': 23,
                                         'position': 'G',
                                         'rebounds': 5,
                                         'teamTricode': 'GSW'}},
         'gameStatus': 2,
         'gameStatusText': 'Q4 09:18',
         'gameTimeUTC': '2022-10-22T02:00:00Z',
         'homeTeam': {'inBonus': '0',
                      'losses': 0,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 34},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 18},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 36},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 5}],
                      'score': 93,
                      'seed': None,
                      'teamCity': 'Golden State',
                      'teamId': 1610612744,
                      'teamName': 'Warriors',
                      'teamTricode': 'GSW',
                      'timeoutsRemaining': 4,
                      'wins': 1},
         'ifNecessary': False,
         'pbOdds': {'odds': 0.0, 'suspended': 0, 'team': None},
         'period': 4,
         'regulationPeriods': 4,
         'seriesGameNumber': '',
         'seriesText': ''},
        {'awayTeam': {'inBonus': '0',
                      'losses': 0,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 28},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 25},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 26},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 9}],
                      'score': 88,
                      'seed': None,
                      'teamCity': 'Phoenix',
                      'teamId': 1610612756,
                      'teamName': 'Suns',
                      'teamTricode': 'PHX',
                      'timeoutsRemaining': 4,
                      'wins': 1},
         'gameClock': 'PT06M58.00S',
         'gameCode': '20221021/PHXPOR',
         'gameEt': '2022-10-21T22:00:00-04:00',
         'gameId': '0022200027',
         'gameLeaders': {'awayLeaders': {'assists': 3,
                                         'jerseyNum': '1',
                                         'name': 'Devin Booker',
                                         'personId': 1626164,
                                         'playerSlug': 'devin-booker',
                                         'points': 23,
                                         'position': 'G',
                                         'rebounds': 5,
                                         'teamTricode': 'PHX'},
                         'homeLeaders': {'assists': 2,
                                         'jerseyNum': '0',
                                         'name': 'Damian Lillard',
                                         'personId': 203081,
                                         'playerSlug': 'damian-lillard',
                                         'points': 35,
                                         'position': 'G',
                                         'rebounds': 3,
                                         'teamTricode': 'POR'}},
         'gameStatus': 2,
         'gameStatusText': 'Q4 06:58',
         'gameTimeUTC': '2022-10-22T02:00:00Z',
         'homeTeam': {'inBonus': '1',
                      'losses': 0,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 25},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 22},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 28},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 14}],
                      'score': 89,
                      'seed': None,
                      'teamCity': 'Portland',
                      'teamId': 1610612757,
                      'teamName': 'Trail Blazers',
                      'teamTricode': 'POR',
                      'timeoutsRemaining': 3,
                      'wins': 1},
         'ifNecessary': False,
         'pbOdds': {'odds': 0.0, 'suspended': 0, 'team': None},
         'period': 4,
         'regulationPeriods': 4,
         'seriesGameNumber': '',
         'seriesText': ''},
        {'awayTeam': {'inBonus': None,
                      'losses': 0,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 35},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 26},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 32},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 31}],
                      'score': 124,
                      'seed': None,
                      'teamCity': 'New Orleans',
                      'teamId': 1610612740,
                      'teamName': 'Pelicans',
                      'teamTricode': 'NOP',
                      'timeoutsRemaining': 0,
                      'wins': 2},
         'gameClock': '',
         'gameCode': '20221021/NOPCHA',
         'gameEt': '2022-10-21T19:00:00Z',
         'gameId': '0022200017',
         'gameLeaders': {'awayLeaders': {'assists': 4,
                                         'jerseyNum': '17',
                                         'name': 'Jonas Valanciunas',
                                         'personId': 202685,
                                         'playerSlug': None,
                                         'points': 30,
                                         'position': 'C',
                                         'rebounds': 17,
                                         'teamTricode': 'NOP'},
                         'homeLeaders': {'assists': 11,
                                         'jerseyNum': '3',
                                         'name': 'Terry Rozier',
                                         'personId': 1626179,
                                         'playerSlug': None,
                                         'points': 23,
                                         'position': 'G',
                                         'rebounds': 8,
                                         'teamTricode': 'CHA'}},
         'gameStatus': 3,
         'gameStatusText': 'Final',
         'gameTimeUTC': '2022-10-21T23:00:00Z',
         'homeTeam': {'inBonus': None,
                      'losses': 1,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 24},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 27},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 34},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 27}],
                      'score': 112,
                      'seed': None,
                      'teamCity': 'Charlotte',
                      'teamId': 1610612766,
                      'teamName': 'Hornets',
                      'teamTricode': 'CHA',
                      'timeoutsRemaining': 0,
                      'wins': 1},
         'ifNecessary': False,
         'pbOdds': {'odds': 0.0, 'suspended': 0, 'team': None},
         'period': 4,
         'regulationPeriods': 4,
         'seriesGameNumber': '',
         'seriesText': ''},
        {'awayTeam': {'inBonus': None,
                      'losses': 1,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 36},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 34},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 32},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 35}],
                      'score': 137,
                      'seed': None,
                      'teamCity': 'San Antonio',
                      'teamId': 1610612759,
                      'teamName': 'Spurs',
                      'teamTricode': 'SAS',
                      'timeoutsRemaining': 0,
                      'wins': 1},
         'gameClock': '',
         'gameCode': '20221021/SASIND',
         'gameEt': '2022-10-21T19:00:00Z',
         'gameId': '0022200018',
         'gameLeaders': {'awayLeaders': {'assists': 5,
                                         'jerseyNum': '25',
                                         'name': 'Jakob Poeltl',
                                         'personId': 1627751,
                                         'playerSlug': None,
                                         'points': 21,
                                         'position': 'C',
                                         'rebounds': 8,
                                         'teamTricode': 'SAS'},
                         'homeLeaders': {'assists': 12,
                                         'jerseyNum': '0',
                                         'name': 'Tyrese Haliburton',
                                         'personId': 1630169,
                                         'playerSlug': None,
                                         'points': 27,
                                         'position': 'G',
                                         'rebounds': 3,
                                         'teamTricode': 'IND'}},
         'gameStatus': 3,
         'gameStatusText': 'Final',
         'gameTimeUTC': '2022-10-21T23:00:00Z',
         'homeTeam': {'inBonus': None,
                      'losses': 2,
                      'periods': [{'period': 1, 'periodType': 'REGULAR',
                                   'score': 26},
                                  {'period': 2, 'periodType': 'REGULAR',
                                   'score': 29},
                                  {'period': 3, 'periodType': 'REGULAR',
                                   'score': 30},
                                  {'period': 4, 'periodType': 'REGULAR',
                                   'score': 49}],
                      'score': 134,
                      'seed': None,
                      'teamCity': 'Indiana',
                      'teamId': 1610612754,
                      'teamName': 'Pacers',
                      'teamTricode': 'IND',
                      'timeoutsRemaining': 0,
                      'wins': 0},
         'ifNecessary': False,
         'pbOdds': {'odds': 0.0, 'suspended': 0, 'team': None},
         'period': 4,
         'regulationPeriods': 4,
         'seriesGameNumber': '',
         'seriesText': ''}
    ]


@pytest.fixture
def video_details_response():
    """Mock response from VideoDetails NBA API endpoint
    """
    return {
        'parameters': {
            'AheadBehind': None,
            'ClutchTime': None,
            'ContextFilter': '',
            'ContextMeasure': 'PTS',
            'DateFrom': None,
            'DateTo': None,
            'EndPeriod': None,
            'EndRange': None,
            'GameID': '0022200016',
            'GameSegment': None,
            'LastNGames': 0,
            'LeagueID': None,
            'Location': None,
            'Month': 0,
            'OppPlayerID': None,
            'OpponentTeamID': 0,
            'Outcome': None,
            'Period': 0,
            'PlayerID': 202695,
            'PointDiff': None,
            'Position': None,
            'RangeType': None,
            'RookieYear': None,
            'Season': '2022-23',
            'SeasonSegment': None,
            'SeasonType': 'Regular Season',
            'StartPeriod': None,
            'StartRange': None,
            'TeamID': 1610612746,
            'VsConference': None,
            'VsDivision': None},
        'resource': 'videodetails',
        'resultSets': {
            'Meta': {
                'videoUrls': [
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'},
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'},
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'},
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'},
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'},
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'},
                    {'dur': None,
                     'lth': None,
                     'ltp': None,
                     'ltt': None,
                     'ltw': None,
                     'mth': None,
                     'mtp': None,
                     'mtt': None,
                     'mtw': None,
                     'sth': None,
                     'stp': None,
                     'stt': None,
                     'stw': None,
                     'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267'}]},
            'playlist': [
                {'d': '20',
                 'dsc': "Leonard 16' Fadeaway Jumper (2 PTS)",
                 'ei': 254,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 36,
                 'hpb': 36,
                 'm': '10',
                 'p': 2,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 50,
                 'vpb': 48,
                 'y': 2022},
                {'d': '20',
                 'dsc': "Leonard 15' Fadeaway Jumper (4 PTS)",
                 'ei': 259,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 36,
                 'hpb': 36,
                 'm': '10',
                 'p': 2,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 52,
                 'vpb': 50,
                 'y': 2022},
                {'d': '20',
                 'dsc': 'Leonard Free Throw 2 of 2 (5 PTS)',
                 'ei': 386,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 60,
                 'hpb': 60,
                 'm': '10',
                 'p': 3,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 61,
                 'vpb': 60,
                 'y': 2022},
                {'d': '20',
                 'dsc': "Leonard 1' Reverse Layup (7 PTS) (Jackson 3 AST)",
                 'ei': 410,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 65,
                 'hpb': 65,
                 'm': '10',
                 'p': 3,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 65,
                 'vpb': 63,
                 'y': 2022},
                {'d': '20',
                 'dsc': "Leonard 27' 3PT Jump Shot (10 PTS) (Wall 2 AST)",
                 'ei': 445,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 65,
                 'hpb': 65,
                 'm': '10',
                 'p': 3,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 74,
                 'vpb': 71,
                 'y': 2022},
                {'d': '20',
                 'dsc': "Leonard 5' Turnaround Bank Hook Shot (12 PTS)",
                 'ei': 643,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 93,
                 'hpb': 93,
                 'm': '10',
                 'p': 4,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 97,
                 'vpb': 95,
                 'y': 2022},
                {'d': '20',
                 'dsc': "Leonard 21' Jump Shot (14 PTS) (George 4 AST)",
                 'ei': 693,
                 'gc': '2022-10-20/LACLAL',
                 'gi': '0022200016',
                 'ha': 'LAL',
                 'hpa': 95,
                 'hpb': 95,
                 'm': '10',
                 'p': 4,
                 'pta': 0,
                 'va': 'LAC',
                 'vpa': 101,
                 'vpb': 99,
                 'y': 2022}]}}


@pytest.fixture
def video_events_assets_response():
    """Mock response from VideoEventsAsset nba api endpoint
    """
    return {
        'parameters': {
            'GameEventID': 783,
            'GameID': '0022200009'
        },
        'resource': 'videoevents',
        'resultSets': {
            'Meta': {
                'videoUrls': [
                    {'ldur': 11700,
                     'lth':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475_1280x720.jpg',
                     'lurl':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475_1280x720.mp4',
                     'mdur': 11700,
                     'mth':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475_960x540.jpg',
                     'murl':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475_960x540.mp4',
                     'scc':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475.scc',
                     'sdur': 11700,
                     'srt':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475.srt',
                     'sth':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475_320x180.jpg',
                     'surl':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475_320x180.mp4',
                     'uuid':
                         '34ebc6be-9491-9a8c-d75d-ede24d605475',
                     'vtt':
                         'https://videos.nba.com/nba/pbp/media/2022/10/19'
                         '/0022200009/783/34ebc6be-9491-9a8c-d75d'
                         '-ede24d605475.vtt'}
                ]
            },
            'playlist': [
                {'d': '19',
                 'dsc': 'MISS Fournier 3PT Jump Shot',
                 'ei': 783,
                 'gc': '2022-10-19/NYKMEM',
                 'gi': '0022200009',
                 'ha': 'MEM',
                 'hid': 1610612763,
                 'hpa': 115,
                 'hpb': 115,
                 'm': '10',
                 'p': 5,
                 'pta': 0,
                 'va': 'NYK',
                 'vid': 1610612752,
                 'vpa': 112,
                 'vpb': 112,
                 'y': 2022
                 }
            ]
        }
    }
