"""Fixtures specific for deciders tests
"""

import pytest
import datetime

from highlights.domain.common import Player, Game, Stats, Team


@pytest.fixture
def ref_top_scorers_decider():
    """reference data for test of TopScorersDecider"""
    return [
        Player(player_id=203081, team_id=1610612757, name='Damian Lillard',
               game=Game(game_id='0022200027',
                         home_team=Team(team_id=1610612757,
                                        full_name='Portland Trail Blazers',
                                        tricode='POR'),
                         away_team=Team(team_id=1610612756,
                                        full_name='Phoenix Suns',
                                        tricode='PHX'),
                         date=datetime.date(2022, 10, 21),
                         status=2),
               stats=Stats(points=35, assists=2, rebounds=3, other=None)),
        Player(player_id=202685, team_id=1610612740, name='Jonas Valanciunas',
               game=Game(game_id='0022200017',
                         home_team=Team(team_id=1610612766,
                                        full_name='Charlotte Hornets',
                                        tricode='CHA'),
                         away_team=Team(team_id=1610612740,
                                        full_name='New Orleans Pelicans',
                                        tricode='NOP'),
                         date=datetime.date(2022, 10, 21),
                         status=3),
               stats=Stats(points=30, assists=4, rebounds=17, other=None)),
        Player(player_id=1630169, team_id=1610612754, name='Tyrese Haliburton',
               game=Game(game_id='0022200018',
                         home_team=Team(team_id=1610612754,
                                        full_name='Indiana Pacers',
                                        tricode='IND'),
                         away_team=Team(team_id=1610612759,
                                        full_name='San Antonio Spurs',
                                        tricode='SAS'),
                         date=datetime.date(2022, 10, 21),
                         status=3),
               stats=Stats(points=27, assists=12, rebounds=3, other=None)),
        Player(player_id=201939, team_id=1610612744, name='Stephen Curry',
               game=Game(game_id='0022200026',
                         home_team=Team(team_id=1610612744,
                                        full_name='Golden State Warriors',
                                        tricode='GSW'),
                         away_team=Team(team_id=1610612743,
                                        full_name='Denver Nuggets',
                                        tricode='DEN'),
                         date=datetime.date(2022, 10, 21),
                         status=2),
               stats=Stats(points=23, assists=4, rebounds=5, other=None)),
        Player(player_id=1626164, team_id=1610612756, name='Devin Booker',
               game=Game(game_id='0022200027',
                         home_team=Team(team_id=1610612757,
                                        full_name='Portland Trail Blazers',
                                        tricode='POR'),
                         away_team=Team(team_id=1610612756,
                                        full_name='Phoenix Suns',
                                        tricode='PHX'),
                         date=datetime.date(2022, 10, 21),
                         status=2),
               stats=Stats(points=23, assists=3, rebounds=5, other=None)),
        Player(player_id=1626179, team_id=1610612766, name='Terry Rozier',
               game=Game(game_id='0022200017',
                         home_team=Team(team_id=1610612766,
                                        full_name='Charlotte Hornets',
                                        tricode='CHA'),
                         away_team=Team(team_id=1610612740,
                                        full_name='New Orleans Pelicans',
                                        tricode='NOP'),
                         date=datetime.date(2022, 10, 21),
                         status=3),
               stats=Stats(points=23, assists=11, rebounds=8, other=None)),
        Player(player_id=1627751, team_id=1610612759, name='Jakob Poeltl',
               game=Game(game_id='0022200018',
                         home_team=Team(team_id=1610612754,
                                        full_name='Indiana Pacers',
                                        tricode='IND'),
                         away_team=Team(team_id=1610612759,
                                        full_name='San Antonio Spurs',
                                        tricode='SAS'),
                         date=datetime.date(2022, 10, 21),
                         status=3),
               stats=Stats(points=21, assists=5, rebounds=8, other=None)),
        Player(player_id=203999, team_id=1610612743, name='Nikola Jokic',
               game=Game(game_id='0022200026',
                         home_team=Team(team_id=1610612744,
                                        full_name='Golden State Warriors',
                                        tricode='GSW'),
                         away_team=Team(team_id=1610612743,
                                        full_name='Denver Nuggets',
                                        tricode='DEN'),
                         date=datetime.date(2022, 10, 21),
                         status=2),
               stats=Stats(points=19, assists=7, rebounds=10, other=None))]
